### ISSUE TITLE
Three Issues with the script

### ISSUE THREAD

**Issue by iFsp3D** [MagdyAboYoussef/AlbionAutoFisher#1]
There are three issues. With the script, the first one is that it's too early. I don't know why, but sometimes I draw the bobber for no reason.
Second thing: sometimes the script will ignore the fish (it doesn't click the fish).
The last thing is that when the minigame is close to ending, the script draws the bobber, and I don't get anything.

**Comment by MagdyAboYoussef** [comment]
Hey I just saw the comment sorry,
first issue: your sound is probably too high lower the game sound a bit until its fine for example 50% or 40% and close the surrounding sounds 

second issue: its not suppose to click the fish, you select the initial spot and it auto throws each time at the same location until you change spot.

third issue:  is probably the pictures I am using and yours aren't exactly similar on both our computers, just update the pictures with pictures you screenshot from your game(bobber.png inside resources folder)
Whats happening is its not detecting the bobber on the screen so its stopping the fishing process. Just update the pictures with your own screenshots and it should work fine.

**Comment by MagdyAboYoussef** [comment]
And its also preferable if you fish in the same biome as the screenshots you take as the brightness matters. 
When I was using it I always fished in forest biomes as it was a bit darker and had the best results.
You can fish in whatever biome you want but just make sure you update the screenshots as the shade of green behind the bobber differs in brightness between biomes so not to confuse it with brightness which was causing your third issue

**Comment by iFsp3D** [comment]
oh Thank you it's works now !

**Comment by MagdyAboYoussef** [comment]
let me know if there's any more issues you facing 👍
